default_language_version:
    python: python3.12
repos:
    - repo: local
      hooks:
      - id: ruff check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types_or: [python, jupyter]
        pass_filenames: false
        args: [.]
    - repo: local
      hooks:
      - id: ruff format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, jupyter]
        pass_filenames: false
        args: [.]
