project:
  title: "python_research_software_templete"
  type: website

publish:
  provider: gh-pages

website:
  title: "quartodoc"
  page-navigation: true
  navbar:
    left:
      - file: tutorials/
        text: Tutorials
      - href: api/
        text: Reference
  sidebar:
    - id: get-started
      title: Get Started
      style: floating
      align: left
      contents:
        - get-started/overview.qmd
        - section: "Docs"
          contents:
            - python_research_software_templete.qmd
        - section: "Tutorials"
          contents:
            - notebook/your_notebook.ipynb

quartodoc:
  style: pkgdown
  package: python_research_software_templete
  dir: api
  sidebar: api/_sidebar.yml
  out_index: index.qmd

  sections:
    - title: sample
      desc: ""
      contents:
        - sample.sample_add_int
