project:
  title: "python_research_software_templete"
  type: website
  render:
    - "*.qmd"

metadata-files:
  - api/_sidebar.yml

publish:
  provider: gh-pages

website:
  title: "python_research_software_templete"
  page-navigation: true
  navbar:
    left:
      - file: index.qmd
        text: Overview
      - href: api/
        text: Reference
  sidebar:
    - id: get-started
      title: Get Started
      style: floating
      align: left
      contents:
        - index.qmd
        - section: "Docs"
          contents:
            - python_research_software_templete.qmd
        - section: "API reference"
          contents:
            - api/index.qmd
        - section: "Notebooks"
          contents:
            - notebook/your_notebook.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

quartodoc:
  style: pkgdown
  package: python_research_software_templete
  dir: api
  sidebar: "api/_sidebar.yml"

  sections:
    - title: sample
      desc: ""
      contents:
        - sample.sample_add_int
