project:
  title: "python_research_software_templete"
  type: website

publish:
  provider: gh-pages

website:
  title: "python_research_software_templete"
  page-navigation: true
  navbar:
    left:
      - file: notebook/your_notebook.html
        text: Notebooks
      - href: api/
        text: Reference
  sidebar:
    - id: get-started
      title: Get Started
      style: floating
      align: left
      contents:
        - sample_page.qmd
        - section: "Docs"
          contents:
            - python_research_software_templete.qmd
            - sample_page.qmd
        - section: "API reference"
          contents:
            - api
        - section: "Notebooks"
          contents:
            - notebook/your_notebook.html

quartodoc:
  style: pkgdown
  package: python_research_software_templete
  dir: api
  sidebar: "api/_sidebar.yml"
  out_index: index.qmd

  sections:
    - title: sample
      desc: ""
      contents:
        - sample.sample_add_int
