[build]
publish = "docs/_site"
command = """
  # 1. Rye をインストール
  chmod +x ./setup-rye.sh && ./setup-rye.sh

  # 2. Quarto をインストール
  curl -Lo quarto.tar.gz https://quarto.org/download/latest/quarto-linux-amd64.tar.gz
  tar -xzf quarto.tar.gz
  export PATH=$PATH:$PWD/quarto/bin  # ダウンロードしたバイナリをパスに追加

  # 3. 必要な Python モジュールをインストール
  source "$HOME/.rye/env"
  rye sync

  # 4. ドキュメントをビルド
  rye run quartodoc build --config docs/_quarto.yml
  find notebook/ -name "*.ipynb" | xargs -I {} basename {} .ipynb | xargs -I {} quarto convert "notebook/{}.ipynb" --output "docs/notebook/{}.qmd"
  quarto render docs
"""
