name: Apply Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  apply_lint_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install uv
        run: ./setup-uv.sh
      - name: Load cached venv
        id: cache_dependency_python
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
      - name: Install python module
        if: ${{ steps.cache_dependency_python.outputs.cache-hit != 'true' }}
        run: |
          uv sync
      - name: Run pre-commit
        run: |
          uv run pre-commit install
          uv run pre-commit run --all-files
      - name: Auto Commit
        if: ${{ always() }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Code Formatter Change
          commit_options: '--no-verify'
      - name: Pytest
        run: |
          uv run pytest -sv tests
